### PR TITLE
Enable spellcheck for rich text editor

### LINKED ISSUE #1769: Add spellcheck to rich text editor
The rich text editor doesn't support spellcheck. Fix that.

### This task is done when...
 - [ ] the rich text editor supports spell check

### PR DESCRIPTION
**Pull request by mgwalker**
### This pull request changes...

- just what it says on the tin
- closes #1769

### This pull request is ready to merge when...

- [x] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [x] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [x] Changelog is updated as appropriate

### This feature is done when...

- [ ] Product has approved the experience

### CODE REVIEW

**Comment by mgwalker** [comment]
Hmm. It _should_ work in IE. The `spellcheck` attribute that this relies on is supported in IE 11. Let me dig into it a bit, but I can definitely replicate it _not_ working in IE.

**Comment by mgwalker** [comment]
It looks like [Draft.js explicitly disables spellcheck in IE 11 and below](https://github.com/facebook/draft-js/issues/640) because of a bug in IE. In a nutshell, IE doesn't provide an event if you right-click the misspelled word and select a correction, so Draft.js doesn't know that anything changed. Then there's a mismatch between what's displayed on the screen and what Draft.js thinks the text is.

For example, let's say you've got this:

> This is text asdf

Conveniently, `asdf` is a typo, so if we enable spellcheck, it'll get a squiggly line. You can right-click on that and choose a corrected spelling. Let's say you choose `ads`. Now this is what you see:

>This is text ads

But IE doesn't send an event, so internally, Draft.js still thinks the text is `This is text asdf`. If you click after `ads` and start typing, IE will start sending events again. That event tells Draft.js _where_ in the text to add letters. So for example, if you type ` abc` at the end, this is what you have visually:

> This is text ads abc

But internally, this is what Draft.js has:

> This is text asd abcf

The ` abc` got inserted at the _same position_ in Draft.js's internal text as it did in the visual text, but the two have different text. Oh no! The visual text will be updated to match Draft.js's internal text whenever the text box is unfocused, and then you could go in and manually fix it, but then what was the point of spellcheck?

Unfortunately, there's simply no solution to this problem. Draft.js made the decision to completely disable spellcheck on IE. The only alternative is to beg users not to use the correction feature in IE and instead manually fix the things that spellcheck identifies.

For usability purposes, I think I have to suggest that we leave it disabled on IE, and I genuinely don't think there's a viable workaround. (There are deeper DOM events that seem to be triggered when the user corrects a spelling with IE's built in right-click thingy and if it's critical, we could investigate whether we could hook those and simulate events into Draft.js to get it to work properly, but I have no idea what that entails offhand.)

**Comment by jeromeleecms** [comment]
OK - I propose we just merge this and then look to our longer term rich text editor (#1408) to incorporate spell check for multiple browsers. That work?

**Comment by mgwalker** [comment]
[It looks like Edge also doesn't fire the right events](https://github.com/facebook/draft-js/issues/990).

**Pull request merged**
