### PR TITLE
APD submission withdrawal frontend

### LINKED ISSUE #849: Build out the withdrawal experience
When a user clicks back into a submitted ADP, they will see this in the Submission section:

screen shot 2018-07-25 at 8 44 53 pm

screen shot 2018-07-25 at 8 47 07 pm

#812 has the design details

### PR DESCRIPTION
**Pull request by mgwalker**
Closes #849 

### This pull request changes...
- adds the APD submission withdrawal experience

screenshot

### This pull request is ready to merge when...
- [x] Tests have been updated (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author

### This feature is done when...
- [x] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by mgwalker** [comment]
Do you mean like actually go to a different page, and then you click to get back to the APD?

**Comment by lauraponce** [comment]
(I also know you're up against the vacation clock so if I should make that into a separate issue for later, please let me know!) 😬

**Comment by lauraponce** [comment]
A different page as in the screen that comes up after you click withdraw so that the top half of this is not there, just the content under the line starting with Your APD submission has been withdrawn:

screen shot 2018-09-12 at 1 39 06 pm

**Comment by mgwalker** [comment]
That should be doable!

**Comment by mgwalker** [comment]
Hides the "submit" section after withdrawing a submission until the user changes something in the APD.  Then it shows the "submit" section and hides the "withdrawal confirmation."

sep-12-2018 17-06-23

**Pull request merged**
