### PR TITLE
Add sidebar padding so it doesn't overlap the scrollbar

### LINKED ISSUE #2155: Add Margin/Padding to scroll bar lane
Spin off from #2105

Add in margin/padding to give some space to the scroll bar while keeping scroll in auto.

### This task is done when...
 - [ ] Padding/Margins set up to test

### PR DESCRIPTION
**Pull request by mgwalker**
### This pull request changes...

- adds 10px of padding to the sidebar
- fixes the height of the sidebar so the scrollbar doesn't go off the bottom
- closes #2155

### This pull request is ready to merge when...

- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate

### This feature is done when...

- [ ] Design has approved the experience

### CODE REVIEW

**Comment by mgwalker** [comment]
Handing this off to y'all to push across the finish line. When y'all are happy with it, feel to merge it so that it goes into staging. See y'all on the other side!

**Comment by pphillips-fearless** [comment]
when on the activity list, you can't scroll all the way up to see the top of the state name.  Is that by design?

**Comment by jeromeleecms** [comment]
I was looking at this earlier, there is a weird bug issue on the original page load, the arrow for expanding program activities is missing. If you click on it, the arrow comes back, but I don't remember seeing this issue in the past:

image

**Comment by pphillips-fearless** [comment]
> I was looking at this earlier, there is a weird bug issue on the original page load, the arrow for expanding program activities is missing. If you click on it, the arrow comes back, but I don't remember seeing this issue in the past:
> 
> image

@jeromeleecms my  understanding is that the arrow for each of the expandable nav sections only shows up when you're on that section.

**Comment by pphillips-fearless** [comment]
It turns out that the scrolling issue I flagged above is only an issue on 2 pages (activity list and private contractor costs) and it's an existing issue that I now see on other branches.  I will approve this change and if the scrolling issue is worth fixing we can make another task for it.

**Comment by jeromeleecms** [comment]
@pphillips-fearless @beparticular @jjames521 I think padding was added to the wrong side of the navbar. In the original issue:

image

It looks like it was added to the right side of the scroll bar instead of the left side. 

image

Am I missing something?

**Comment by beparticular** [comment]
@jeromeleecms i think it's correct. in staging the scroll bar appears to be touching the arrow, while in the preview here, it's ever so slightly not which is what was intended. this is based on what I'm seeing in Chrome.

**Pull request merged**
