### PR TITLE
Make help text visible only on screen

### LINKED ISSUE #1349: Remove helptext and reminders from print view
Remove helptext and reminders from print view because they add a lot of unnecessary text that aren't useful when reviewing an APD.

From #1160

### This task is done when...
 - [ ] helptext and reminders are hidden in print view

### PR DESCRIPTION
**Pull request by mgwalker**
### This pull request changes...
- makes help text in instructions hidden in print view
- closes #1349

### This pull request is ready to merge when...
- [ ] Tests have been updated (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated

### This feature is done when...
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by mgwalker** [comment]
@NAretakis @jeromeleecms Did we test the PDFs at State HIT Connect to decide which parts of the instruction/help text to hide?

**Comment by jeromeleecms** [comment]
Sadly, we didn't. Will have to try and schedule to do it this sprint. 

_Jots note for today's sprint planning._

**Comment by CSwartzHMA** [comment]
Can/Should this be done in conjunction with #1316 ? I am actually working on this today and can provide some feedback.

**Comment by jeromeleecms** [comment]
@CSwartzHMA Did you get any feedback on this, yet?

**Comment by CSwartzHMA** [comment]
I had sent a note. I tried to test, but the APDs I can see in the app currently are blank so I wanted to try to find one that is completed for testing.

**Comment by mgwalker** [comment]
Going to merge this one (removes help text in print) so it doesn't get stale, but will leave #1349 open until we're sure we've removed all the right bits of text.

**Pull request merged**
