### PR TITLE
Help text reconfig & rewrites [skip deploy]

### PR DESCRIPTION
**Pull request by quarterback**
Post-user testing issue related to highlighting help text. This PR moves help text into the reminder section. 

### This pull request changes...
- Solves issue #952 & #968

### This pull request is ready to merge when...
- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated

### This feature is done when...
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by quarterback** [comment]
Don't merge this yet, I just wanted to push it so I could see a live version of my changes so far.

**Comment by quarterback** [comment]
More updates made.

**Comment by lauraponce** [comment]
@quarterback will this one include help text changes related to #948? If so, I'll close that one out

**Comment by quarterback** [comment]
I think I found the validation error inside the yaml file, it's valid now so hopefully it'll pass and we can push this out.

**Comment by quarterback** [comment]
@mgwalker @brendansudol I fixed one of the validation error, but I can't figure out what's making circleci fail.

**Comment by NAretakis** [comment]
So much here. Thanks @quarterback

**Comment by brendansudol** [comment]
don't merge yet

**Pull request merged**
