### PR TITLE
Always save the APD

### PR DESCRIPTION
**Pull request by pphillips-fearless**
Update the APD validation schema so that dates can be saved as any text instead of being validated as dates. Will we do informational validation as a separate step in the future. Schema validation failures will be considered client-side data failures rather than user errors.

### This pull request changes...

- updated APD schema to allow dates of any string format
- added endpoint test

### This pull request is ready to merge when...

- [x] Tests have been updated (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author
~~- [ ] The change has been documented~~
~~- [ ] Associated OpenAPI documentation has been updated~~
- [ ] Changelog is updated as appropriate

### CODE REVIEW

**Comment by mgwalker** [comment]
I don't think there's anything to document in this change, and the OpenAPI should still be the same. The only thing left is to add a line to the changelog.

**Comment by jeromeleecms** [comment]
Saves as intended! Clarification on the behavior -- (maybe need to spin this into a separate issue): 

1. Entered the invalid data into the date field (check)
2. System calls out invalid data

image

3. The system saved as expected (even with the invalid data)
4. Close out of the APD and come back
5. Revisit the invalid date, error message is gone.

image

Should the app be revalidated form entry on load so it can identify potential error that were saved? I can be OK with approving this as is because it's scoped as saving everything, but I would want to track how to get appropriate error messages to appear when revisiting an APD that contains invalid data.

@pphillips-fearless @mgwalker

**Comment by mgwalker** [comment]
I think my opinion would be to create a new issue and remove that error message altogether. We only put it in because invalid dates would cause the save to fail, and we were trying to highlight for the user what went wrong. Now that's no longer the case and we accept anything. We can put this validation back when we do the larger info-validation work in the future.

@pphillips-fearless @lauraponce Interested what y'all think too.

**Comment by lauraponce** [comment]
I agree with @jeromeleecms that it seems strange to just have the error message go away forever, it seems like this could fit into #2092 for thinking about how to handle errors as a whole. Does that seem right, @mgwalker and @jeromeleecms to call it out in 2092 for figuring out a solution to this and closing this PR?

**Pull request merged**
