### PR TITLE
Fix white gap under small cards

### PR DESCRIPTION
**Pull request by hbillings**
Greg noticed this on the footer PR, but I couldn't reproduce it locally. Now I see it! So I fixed it!

### This pull request is ready to merge when...
- [x] This code has been reviewed by someone other than the original author

### CODE REVIEW

**Comment by jeromeleecms** [comment]
@hbillings I just spun up a bug under #1540 for this, does this also solve the issue described there?

**Comment by mgwalker** [comment]
FWIW, I still see the gap on a normal-sized window on my external monitor. The height of the white gap is proportional to the height of the window, so if I make it exaggeratedly tall, the gap gets huge, or the gap goes away entirely if I shorten the window height.

**Comment by hbillings** [comment]
@mgwalker I think in order to address that, we're going to need to find a way to make the page background gray, rather than the current solution which changes the color of the card container background. The only way I know of to for sure fix it the way it currently exists is to set the card container to `height: 100vh`, which will always push the footer off the page, even when there's not much content in the card. Maybe that looks less weird than a gap?

**Comment by mgwalker** [comment]
Oof, setting the page background would be a _thing_...  It's outside the React ecosystem, so we could use some DOM APIs to do it, but I'm not sure where would be the right place to do that.  It almost seems like the only place we could reliably do it would be in the route handler.  🤔

OH!  OH!  This might be a good use of a context - they're essentially a way of creating global state within a React app.  https://reactjs.org/docs/context.html  The `Wrapper` could add a class to the `<div className="site">` based on the value in the context?

**Pull request merged**
