### PR TITLE
Fix Sass warnings

### LINKED ISSUE #1774: Sass build warnings
When the app builds, the Sass step produces some warnings about missing variables without fallbacks. For example:

screenshot showing warnings

The build does complete and everything seems to be working fine, but we should fix the warnings.

### This task is done when...
 - [ ] warnings are fixed

### PR DESCRIPTION
**Pull request by mgwalker**
We had rounded borders applied to some parts of the rich text editor, but those borders were based on a radius variable that was set in the legacy CSS index file. When that file went away, the variables were no longer defined, so Sass would give us a warning. Since nobody seemed to notice or mind that the borders were no longer rounded, I opted to just remove them rather than put the variable back.

### This pull request changes...

- removes references to `--border-radius` variable in scss
- closes #1774

### This pull request is ready to merge when...

- [x] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- ~Changelog is updated as appropriate~ Not necessary. This is part of removing the old styles, which is already in the changelog

### CODE REVIEW

**Comment by hbillings** [comment]
I wonder if, instead of just removing the old variable, it would make sense to replace it with the `$border-radius` variable that the other form fields use? That way we'll maintain consistent radii throughout.

**Comment by mgwalker** [comment]
Perhaps! We could ask Laura to weigh in? I chose to just take them out because that wouldn't have any affect on the visuals, but maybe it was a regression when the rounded borders stopped working in the first place. 😬

**Comment by hbillings** [comment]
@mgwalker We do still have rounded borders! They're just 3px rounded instead of IIRC 6px. Oddly, when I pulled this branch down and recompiled the Sass, it still showed the correct 3px, but I couldn't for the life of me figure out where it was coming from, since there's no actual input box in the RTE. Maybe we can merge this as-is, and if the RTE ends up showing square corners, we can fix it then?

**Comment by mgwalker** [comment]
How very odd... Maybe it's built into the RTE's stylesheets? Anyway, I like that plan.

**Pull request merged**
