### PR TITLE
Key personnel reminder text & help text reversions

### PR DESCRIPTION
**Pull request by quarterback**
For both #1001 (yaml reversion) & #1005 (key personnel)

### This pull request changes...
- help text changes reverts reminder text to help text, with additional changes.
- wrote reminder text for key personnel section

### This pull request is ready to merge when...
- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated

### This feature is done when...
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by NAretakis** [comment]
Content good, formatting seems wonky, can you check?

image

**Comment by quarterback** [comment]
> Content good, formatting seems wonky, can you check?
> 
> image
Yes! That is not supposed to look that way. On it.

**Comment by quarterback** [comment]
Fixed! 
screenshot 2018-09-12 10 40 41

**Comment by NAretakis** [comment]
I like it. Nice work! Relatedly, I do think some of our helptext sections are a little long or are good candidates for bulleted lists. I know we have an issue somewhere to allow formatting within helptext, and it might be something good for us to think about how to break up some of ones with longer descriptions.

**Comment by quarterback** [comment]
@NAretakis I'll spin up an issue related to formatting and can test to see how much formatting works, right now, I've just numbered lists because it wasn't allowed before but we can try other formatting tweaks.

**Pull request merged**
