### PR TITLE
Show a more meaningful save error if the user is logged out

### LINKED ISSUE #1729: If save fails because the user is logged out, tell them so instead of using the generic save failed message
If the user is logged out, the returned status code is 403. Any other failure would be a 400, 401, or 404. If a save fails and the response code is 403, we can display a different message to the user so they have a better understanding of how to fix the problem.

(Related to #1728, in that once #1728 is fixed, the user should only run into this issue if the frontend idle timeout is longer than the backend timeout, which would be a misconfiguration. Still, worth adding in, I think.)

### This task is done when...
 - [ ] attempting to save while logged out shows a different error message

### PR DESCRIPTION
**Pull request by mgwalker**
We can detect if the save fails due to the user being logged out, so we should give them a more useful error message.

### This pull request changes...

- give them a more useful error message
   Screen Shot 2019-08-05 at 12 09 03 PM
- closes #1729 

### This pull request is ready to merge when...

- [x] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [x] Changelog is updated as appropriate

### This feature is done when...

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by mgwalker** [comment]
@jeromeleecms Yes, that'd be a good long-term change! There are some internal architectural changes we'd need to make to support it, but the user experience would definitely be better.

**Comment by quarterback** [comment]
@jeromeleecms @mgwalker I'll propose another mod of the text for brevity and consistency with other text. _"**Save failed**: You are logged out. Use another tab to login, and try saving again."_

**Comment by mgwalker** [comment]
Text changed to "Save failed: You are logged out. Use another tab to login, and try saving again." and moved into the yaml (`errors.yaml`, `save-apd.not-logged-in`)

**Comment by mgwalker** [comment]
That's the expected behavior. If there aren't any changes in the first tab, it won't actually try to save anything to the API and instead just says it was successful.

**Pull request merged**
