### PR TITLE
Help text culling

### PR DESCRIPTION
**Pull request by quarterback**
### This pull request changes...

- Truncated and removed excess text to improve navigation and clarity across the app user experience.
- Related to Issue #1567 

### This pull request is ready to merge when...

- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate

### This feature is done when...
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by mgwalker** [comment]
There's a bunch of stuff cut out here, and I'm curious if we might eventually want to add it back in a less-intrusive way (maybe a little `?` button or something users can click to expand longer help text). If so, would it make sense to create a new issue about that, reference this one (so we'll have a link back to the longer text), and then throw the new issue into the icebox?

**Comment by quarterback** [comment]
@mgwalker Yes, good call. I created #1817 but it could be worded better or more accurately.

**Comment by quarterback** [comment]
The rationale for this PR:

- Culls the content from the blue additional help sections of the application to make it easier to flow through the app.
- If users are already trained in doing APDs and are using the real template to get instructions that are more current, do we need to repeat that content inside the application?
- By removing the content and testing it with users, will we discover that they're not paying attention to it being gone at all? If so, that might make it easier to design an experience that's even easier to navigate down the road? 
- A/B testing will give us an opportunity for real data around whether it's _actually_ helpful or not to have this information or whether we ought to implement new data/information into the application. 
- For A/B purposes, just using the deploy URLs will be easier than spinning a separate instance of the app. 

cc: @jeromeleecms @lauraponce

**Comment by lauraponce** [comment]
It looks like some of the labels got taken out with the help text in the Standards and Conditions section:

Screen Shot 2019-10-16 at 8 44 33 PM

@jeromeleecms I think we should hold off on this PR for now since we're making the other big changes to the activities section. What do you think?

**Comment by jeromeleecms** [comment]
Closing this one - we will revisit the content later.

**Pull request closed without merging**
