### PR TITLE
APD versions model and initial endpoint

### PR DESCRIPTION
**Pull request by mgwalker**
- Adds an APD versions database table and model
- Adds an endpoint at `POST /apds/:id/versions` to create a new version - this will also set the APD's status to `in review`
- Updates the `userCanEditAPD` middleware to fail if the APD status is not `draft`

### This pull request changes...
- no visible changes yet!

### This pull request is ready to merge when...
- [x] Tests have been updated (and all tests are passing) - needs tests for the new endpoint
- [ ] This code has been reviewed by someone other than the original author
- [x] The change has been documented
  - [x] Associated OpenAPI documentation has been updated

### This feature is done when...
- [ ] Product has approved the experience: cc @jeromeleecms @NAretakis

### CODE REVIEW

**Comment by NAretakis** [comment]
If we end up with a version number, or version code thingy, it might be worth putting that at the top of the page somewhere. I remember testers interested in seeing that they are working on "Version 1" or something. We might need to come up with a version naming convention.

**Comment by NAretakis** [comment]
How about:
[State Code][Program]APDv[version number]
or
TX-HITECH-APD-v6
Thoughts @jeromeleecms ?

**Comment by mgwalker** [comment]
Would this version number be for states to see as they're drafting it, or for CMS staff to see as they're reviewing it?  Or both?  (Logical OR versus semantic "or"!)

**Comment by NAretakis** [comment]
Version stuff is for both States and CMS I think.

**Pull request merged**
