### PR TITLE
better login fail handing

### PR DESCRIPTION
**Pull request by brendansudol**
* Now checks for `error.response` (network errors did not have a response so this was a throwing an error inside the catch block)

* A more generic and better styled error message if something failed while logging in. (We can abstract this into a `Message` or `Alert` component once we have a couple more examples and design guidance)

Once we have better custom error messages, we can sub those in easily into the UI via the `auth.error` store value.

### This pull request is ready to merge when...
- [x] Tests have been updated (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- ~The change has been documented~
  - ~Associated OpenAPI documentation has been updated~

### This feature is done when...
- [x] Design has approved the experience
- ~Product has approved the experience~

Preview:
login-fail

### CODE REVIEW

**Comment by brendansudol** [comment]
cc: @lauraponce

**Comment by lauraponce** [comment]
@brendansudol is the plan to eventually use the USWDS styles for the form elements? Either way is fine, I was just wondering! 

I like where this is going, is there a way to soften the red notification and tie it to the fields? Maybe by outlining the form fields to show where there is an issue and displaying the message in red text without the fill? 

screen shot 2018-03-08 at 9 43 09 am

**Comment by brendansudol** [comment]
yes, we can cherrypick any of the USWDS styles we like, as well as change / supplement with our own.

Yes, I definitely agree about having per-field notifications (vs. the one big, vague global one at the top)

That is work we should absolutely slot in shortly -- for now, I'm just hoping to slightly improve what's currently there.

**Comment by brendansudol** [comment]
Softened the red, and made more in line with uswds:

screen shot 2018-03-08 at 10 06 13 am

**Comment by brendansudol** [comment]
If you're comfortable with this direction / improvement @lauraponce, you'll have to explicitly "approve" this pull request before it gets added to the site. If you're not comfortable, that's fine too (and we can iterate)!

**Pull request merged**
