### PR TITLE
Added ordered lists

### PR DESCRIPTION
**Pull request by quarterback**
Describe the pull request here, including any supplemental information needed to understand it.

### This pull request changes...
- Ordered lists for key personnel and cost allocation sections.

### This pull request is ready to merge when...
- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated

### This feature is done when...
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by hbillings** [comment]
I'm good with this as soon as @mgwalker's changes get merged in!

**Comment by mgwalker** [comment]
@hbillings I pushed them directly in 61fea90

**Comment by quarterback** [comment]
@jeromeleecms Sure!

**Comment by jeromeleecms** [comment]
@quarterback I'm not seeing the added line break...?

**Comment by mgwalker** [comment]
@jeromeleecms There was a YAML formatting bug, so it didn't re-deploy after Ron added the line break. I fixed the YAML so it should be updated shortly. When you see the bot's comment updated with `c8f476a` at the bottom, it's ready to go.

**Pull request merged**
