### PR TITLE
Key personnel help text change

### PR DESCRIPTION
**Pull request by quarterback**
### This pull request changes...
- Changed the text in key personnel from a single paragraph to an numbered list

### This pull request is ready to merge when...
- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated

### This feature is done when...
- [ ] Design has approved the experience
- [x] Product has approved the experience

### CODE REVIEW

**Comment by mgwalker** [comment]
@quarterback A couple of things, in case they're relevant for this PR:
- if you want a blank line in the rendered text, you have to do two blank lines in the YAML because :waves-hands: (I think it's an actual Markdown thing because of how it handles breaks)

```
1. first point here


2. second point here
```

- We added support for real lists! If you want a numbered list instead of some paragraphs that are preceded by numbers:

```
[ol]
item 1

item 2

item 3
[/ol]
```

  We also support bulleted lists with `[ul]`

**Comment by quarterback** [comment]
@mgwalker I'll update this with list support, didn't realize things were fancy around here now. Thanks!

**Comment by lauraponce** [comment]
@quarterback Resurrecting this one for a quick question – it looks like the ordered list made it to the Modularity section, but it doesn't look like it's showing up correctly for the Cost Allocation section or the Key Personnel text where the numbers are part of the content. Is that related to this or something different?

Screen Shot 2019-07-17 at 1 41 42 PM

Screen Shot 2019-07-17 at 1 42 10 PM

Screen Shot 2019-07-17 at 1 41 33 PM

**Comment by quarterback** [comment]
@lauraponce Let me take a look at the yaml!

**Pull request merged**
