### PR TITLE
fix apd blank screen

### PR DESCRIPTION
**Pull request by brendansudol**
fixes: https://github.com/18F/cms-hitech-apd/issues/802

if you land on `/apd` page, it redirects you to homepage so that you can select an apd of your choosing.

### This pull request is ready to merge when...
- [x] Tests have been updated (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author

### This feature is done when...
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by jeromeleecms** [comment]
Should it take you to the main dashboard or can it keep you on the APD that you are currently working on?

**Comment by mgwalker** [comment]
Maybe we should leave #802 open.  This is just to eliminate the blank screen - the app will do *something*.  Getting the local storage stuff - so you can reload and be looking at the same APD - might take a little more time to do right (there are some issues with timing that might be hard to figure out).

Does this seem like a reasonable stopgap?

**Comment by brendansudol** [comment]
right now it does the former @jeromeleecms; if we get annoyed by that and want to move to latter, we can certainly do that in time (it's a little trickier)

**Comment by jeromeleecms** [comment]
Works for me! Let’s keep #802 open, though. At least the app does stop working now.

**Pull request merged**
